/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmrRouteImport } from './routes/emr'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CmeRouteImport } from './routes/cme'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AffiliationsRouteImport } from './routes/affiliations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferralsIndexRouteImport } from './routes/referrals.index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as ReferralsNewRouteImport } from './routes/referrals.new'
import { Route as ReferralsReferralIdRouteImport } from './routes/referrals.$referralId'
import { Route as PlatformReportsRouteImport } from './routes/platform.reports'
import { Route as PlatformInstitutionsRouteImport } from './routes/platform.institutions'
import { Route as PlatformDoctorsRouteImport } from './routes/platform.doctors'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform.analytics'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as OnboardingPendingRouteImport } from './routes/onboarding_.pending'
import { Route as HospitalDoctorsRouteImport } from './routes/hospital.doctors'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmrRoute = EmrRouteImport.update({
  id: '/emr',
  path: '/emr',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CmeRoute = CmeRouteImport.update({
  id: '/cme',
  path: '/cme',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliationsRoute = AffiliationsRouteImport.update({
  id: '/affiliations',
  path: '/affiliations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReferralsRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorsRoute,
} as any)
const ReferralsNewRoute = ReferralsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReferralsRoute,
} as any)
const ReferralsReferralIdRoute = ReferralsReferralIdRouteImport.update({
  id: '/$referralId',
  path: '/$referralId',
  getParentRoute: () => ReferralsRoute,
} as any)
const PlatformReportsRoute = PlatformReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformInstitutionsRoute = PlatformInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDoctorsRoute = PlatformDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PlatformRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const OnboardingPendingRoute = OnboardingPendingRouteImport.update({
  id: '/onboarding_/pending',
  path: '/onboarding/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDoctorsRoute = HospitalDoctorsRouteImport.update({
  id: '/hospital/doctors',
  path: '/hospital/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => DoctorsRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliations': typeof AffiliationsRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/availability': typeof AvailabilityRoute
  '/billing': typeof BillingRoute
  '/cme': typeof CmeRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/emr': typeof EmrRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/patients': typeof PatientsRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/doctors': typeof PlatformDoctorsRoute
  '/platform/institutions': typeof PlatformInstitutionsRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/referrals/$referralId': typeof ReferralsReferralIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliations': typeof AffiliationsRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/availability': typeof AvailabilityRoute
  '/billing': typeof BillingRoute
  '/cme': typeof CmeRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/emr': typeof EmrRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/doctors': typeof PlatformDoctorsRoute
  '/platform/institutions': typeof PlatformInstitutionsRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/referrals/$referralId': typeof ReferralsReferralIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/doctors': typeof DoctorsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/referrals': typeof ReferralsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliations': typeof AffiliationsRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/availability': typeof AvailabilityRoute
  '/billing': typeof BillingRoute
  '/cme': typeof CmeRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/emr': typeof EmrRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/patients': typeof PatientsRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/onboarding_/pending': typeof OnboardingPendingRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/doctors': typeof PlatformDoctorsRoute
  '/platform/institutions': typeof PlatformInstitutionsRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/referrals/$referralId': typeof ReferralsReferralIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliations'
    | '/analytics'
    | '/appointments'
    | '/auth-callback'
    | '/availability'
    | '/billing'
    | '/cme'
    | '/dashboard'
    | '/discussions'
    | '/doctors'
    | '/emr'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/patients'
    | '/platform'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/doctors/$doctorId'
    | '/hospital/doctors'
    | '/onboarding/pending'
    | '/patients/$patientId'
    | '/platform/analytics'
    | '/platform/doctors'
    | '/platform/institutions'
    | '/platform/reports'
    | '/referrals/$referralId'
    | '/referrals/new'
    | '/doctors/'
    | '/patients/'
    | '/platform/'
    | '/referrals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliations'
    | '/analytics'
    | '/appointments'
    | '/auth-callback'
    | '/availability'
    | '/billing'
    | '/cme'
    | '/dashboard'
    | '/discussions'
    | '/emr'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/doctors/$doctorId'
    | '/hospital/doctors'
    | '/onboarding/pending'
    | '/patients/$patientId'
    | '/platform/analytics'
    | '/platform/doctors'
    | '/platform/institutions'
    | '/platform/reports'
    | '/referrals/$referralId'
    | '/referrals/new'
    | '/doctors'
    | '/patients'
    | '/platform'
    | '/referrals'
  id:
    | '__root__'
    | '/'
    | '/affiliations'
    | '/analytics'
    | '/appointments'
    | '/auth-callback'
    | '/availability'
    | '/billing'
    | '/cme'
    | '/dashboard'
    | '/discussions'
    | '/doctors'
    | '/emr'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/patients'
    | '/platform'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/doctors/$doctorId'
    | '/hospital/doctors'
    | '/onboarding_/pending'
    | '/patients/$patientId'
    | '/platform/analytics'
    | '/platform/doctors'
    | '/platform/institutions'
    | '/platform/reports'
    | '/referrals/$referralId'
    | '/referrals/new'
    | '/doctors/'
    | '/patients/'
    | '/platform/'
    | '/referrals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliationsRoute: typeof AffiliationsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BillingRoute: typeof BillingRoute
  CmeRoute: typeof CmeRoute
  DashboardRoute: typeof DashboardRoute
  DiscussionsRoute: typeof DiscussionsRoute
  DoctorsRoute: typeof DoctorsRouteWithChildren
  EmrRoute: typeof EmrRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  HospitalDoctorsRoute: typeof HospitalDoctorsRoute
  OnboardingPendingRoute: typeof OnboardingPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emr': {
      id: '/emr'
      path: '/emr'
      fullPath: '/emr'
      preLoaderRoute: typeof EmrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cme': {
      id: '/cme'
      path: '/cme'
      fullPath: '/cme'
      preLoaderRoute: typeof CmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliations': {
      id: '/affiliations'
      path: '/affiliations'
      fullPath: '/affiliations'
      preLoaderRoute: typeof AffiliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof ReferralsRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/referrals/new': {
      id: '/referrals/new'
      path: '/new'
      fullPath: '/referrals/new'
      preLoaderRoute: typeof ReferralsNewRouteImport
      parentRoute: typeof ReferralsRoute
    }
    '/referrals/$referralId': {
      id: '/referrals/$referralId'
      path: '/$referralId'
      fullPath: '/referrals/$referralId'
      preLoaderRoute: typeof ReferralsReferralIdRouteImport
      parentRoute: typeof ReferralsRoute
    }
    '/platform/reports': {
      id: '/platform/reports'
      path: '/reports'
      fullPath: '/platform/reports'
      preLoaderRoute: typeof PlatformReportsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/institutions': {
      id: '/platform/institutions'
      path: '/institutions'
      fullPath: '/platform/institutions'
      preLoaderRoute: typeof PlatformInstitutionsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/doctors': {
      id: '/platform/doctors'
      path: '/doctors'
      fullPath: '/platform/doctors'
      preLoaderRoute: typeof PlatformDoctorsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/onboarding_/pending': {
      id: '/onboarding_/pending'
      path: '/onboarding/pending'
      fullPath: '/onboarding/pending'
      preLoaderRoute: typeof OnboardingPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/doctors': {
      id: '/hospital/doctors'
      path: '/hospital/doctors'
      fullPath: '/hospital/doctors'
      preLoaderRoute: typeof HospitalDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DoctorsRouteChildren {
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

interface PlatformRouteChildren {
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformDoctorsRoute: typeof PlatformDoctorsRoute
  PlatformInstitutionsRoute: typeof PlatformInstitutionsRoute
  PlatformReportsRoute: typeof PlatformReportsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  PlatformDoctorsRoute: PlatformDoctorsRoute,
  PlatformInstitutionsRoute: PlatformInstitutionsRoute,
  PlatformReportsRoute: PlatformReportsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface ReferralsRouteChildren {
  ReferralsReferralIdRoute: typeof ReferralsReferralIdRoute
  ReferralsNewRoute: typeof ReferralsNewRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
}

const ReferralsRouteChildren: ReferralsRouteChildren = {
  ReferralsReferralIdRoute: ReferralsReferralIdRoute,
  ReferralsNewRoute: ReferralsNewRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
}

const ReferralsRouteWithChildren = ReferralsRoute._addFileChildren(
  ReferralsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliationsRoute: AffiliationsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AvailabilityRoute: AvailabilityRoute,
  BillingRoute: BillingRoute,
  CmeRoute: CmeRoute,
  DashboardRoute: DashboardRoute,
  DiscussionsRoute: DiscussionsRoute,
  DoctorsRoute: DoctorsRouteWithChildren,
  EmrRoute: EmrRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  HospitalDoctorsRoute: HospitalDoctorsRoute,
  OnboardingPendingRoute: OnboardingPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
